### ISSUE TITLE
Temperature change compatibility

### ISSUE THREAD

**Issue by TheWeatherPony** [EnviroMine/EnviroMine-1.7#105]
When getting the temperature of a biome, the mod is currently retrieving the value from the biome's field. Acquiring it like this bypasses mods that change the temperature by altering the biome's method getFloatTemperature(III)F, such as my own. Could you please make the mod call the method, instead of getting the temperature directly from the field?

**Comment by thislooksfun** [comment]
I don't know why we're doing that, but we'll look into it. Thanks for the heads up!

**Comment by PitchBright** [comment]
Does that mean Enviromine isn't drawing the correct temperature from biomes that have their temperatures controlled by other mods?

**Comment by thislooksfun** [comment]
It would appear to mean that, yes.

**Comment by PitchBright** [comment]
Oh jumpin's! :( 
That renders the whole temperature functionality of Enviromine useless. Is that an easy thing to fix?

**Comment by thislooksfun** [comment]
I didn't say that it actually did, I'm saying that it might. Yes, it's an easy fix, but I have been busy (and lazy) lately. I'll look into it tonight if I have time, remember, and am not feeling lazy. \:P

**Comment by PitchBright** [comment]
Roger that. Thanks dude. The cheque is in the mail ;-)

**Comment by thislooksfun** [comment]
The cheque is... huh? Am I being ignorant of some slang here? XD

**Comment by PitchBright** [comment]
Oh, haha. It's a funny way of saying "The money is on it's way".

**Comment by thislooksfun** [comment]
Hey @TheWeatherPony, are the args for getFloatTemperature x,y,z?

**Comment by TheWeatherPony** [comment]
yep. vanilla changes the temperature based on the location, but only if  y>64 (which you could take advantage of, if you wanted)
If there's three ints together, good chance it's a location. :)

**Comment by thislooksfun** [comment]
Yeah, I figured it out just after asking you. XP
Anyway, it is pending release. Should be in the next version if I didn't break anything too badly. XD

**Comment by PitchBright** [comment]
That's awesome! Thanks for fixing that up so quickly, TLF.

**Comment by thislooksfun** [comment]
Like I said, it was an easy fix, we've just been lazy. \:P

**Comment by PitchBright** [comment]
Did this fix make it into any of the post-v1.3.111 updates? I don't see any mention of it in the changelogs.

**Comment by thislooksfun** [comment]
It appears that it has not. Hey @Funwayguy, there are pending changes on PreRelease. Could merge them next update?

**Comment by PitchBright** [comment]
Fix for the biome temperature issue not included, or is it not listed?


[#114]------------------------------------------

Important make backups of your config before loading the game!

+ New Add Custom "shift + j" functionality.  It now adds objects to the correct mod config file
+ New Add Custom Gui for easier editing and selecting of items in custom configs
+ New Config Layout (With legacy support to convert your old games)
+ New Profile System per world. Now you can have different physics ect.. depending on which world you load.
* Fixed Mod Identification putting vanilla biomes into unknown.cfg
+ New Button Update notification in the main menus.

Conflicts:
 src/main/java/enviromine/core/EM_Settings.java

**Comment by thislooksfun** [comment]
It appears that only one file was actually updated in that... We're working on sorting it out.

**Comment by TheWeatherPony** [comment]
Take any longer and I might just force minimal compatibility on your end though my code, until you fix it :P
(Seriously - this isn't a difficult issue to fix, and it's taken almost two months already.)

**Comment by thislooksfun** [comment]
I'm sorry it's taking so long I thought for sure someone would have pushed the updates to master before now.

**Comment by GenDeathrow** [comment]
To be honest I thought it was already fixed when I pushed the last update. or I would have gotten it / made sure it was on their.

**Comment by thislooksfun** [comment]
I thought it was too, but it seems to have magically vanished somehow. Someone probably pushed some files without checking to see if they had been updated.

**Comment by thislooksfun** [comment]
Done! It's in the latest build.

**Comment by TheWeatherPony** [comment]
Thanks. I know my users will really appreciate it :)

**Comment by PitchBright** [comment]
Dudes… 5 months later. Still not workin'.

https://github.com/EnviroMine/EnviroMine-1.7/blob/master/src/main/java/enviromine/utils/EnviroUtils.java
line 164

line 168 is what it should be calling, but it's clearly not
in order to be compatible, it needs to never call BiomeGenBase.temperature

simplest fix is to change line 166 to the following:
return getBiomeTemp(0,0,0,biome);

**Comment by GenDeathrow** [comment]
Thanks for noticing that... https://github.com/EnviroMine/EnviroMine-1.7/blob/master/src/main/java/enviromine/utils/EnviroUtils.java#L164-L167

I reopen this and try and get it on the next update.. it technically worked as long as you called (x,y,z,biome).. it was probably just an over site we had missed. Everyone has been busy with a lot of big life changes, the last couple of months.. the whole team. But I am glad you pointed it out.. cause I was trying to clear out some old bugs and some bugs I cant remember if they were fixed or not...

**Comment by PitchBright** [comment]
I'm muckin' around with it right now… and I'm not convinced that the change I suggested, is the entire solution there. I need to test it against something else that changes the temperatures, so that I can see for sure if the suggested change does the trick.

(PS. You guys really need to use IRC :P )

**Comment by TheWeatherPony** [comment]
Got together with GenDeathrow and PitchBright in IRC to work things out. The problem is currently partially in both my code and in Enviromine. Both projects have an easy, tiny fix to be included, and neither project will require the other to develop or run after making the change. My code will, however, need to have a String reference to the getSurroundingData method in enviromine.handlers.EM_StatusManager, and will need to be updated should said method stop existing in it's current form (class name, method name, and method description [parameter and return types]).

**Comment by TheWeatherPony** [comment]
Resolved with commit 028dafd8da453dc089bff2808da33281aff0aed5
The Seasons Mod is performing the rest of the temperature integration with builds made  September 20th, 2015, and later.

**Comment by PitchBright** [comment]
Needs re-opening.

@GenDeathrow 
I just tested a clean install of TSM + EM122 and I get this crash (singleplayer)
http://pastebin.com/bsasL3Pw

**Comment by PitchBright** [comment]
Update: I think it is working, and I misreported that it wasn't. Disregard for now, I'll continue to test the Temperature stuff extensively, and report back if I encounter any issues. Sorry 'bout that.
