### ISSUE TITLE
Earthquake crash

### ISSUE THREAD

**Issue by jasonsaffle13** [EnviroMine/EnviroMine-1.7#98]
On our multi player server earth quakes cause crashes.  version 1.3.103

**Comment by GenDeathrow** [comment]
think you could give a crash report. It will be hard/impossible to pin point it down with out it. If you get it.. make sure to use something like http://pastebin.com/ to add it. It will be easier for us to read.. than just put link here.

**Comment by jasonsaffle13** [comment]
I turned earth quakes back on in config as soon as another one happens will post unless there is a command to cause one.

**Comment by 710583** [comment]
Doesn't your server keep event logs?

**Comment by jasonsaffle13** [comment]
The server is on my desktop for the wife, kids, and a couple of my friends, I did find a log of the crash but i had cleared the crash report :-( 
http://paste.ubuntu.com/10281840/

**Comment by GenDeathrow** [comment]
@jasonsaffle13  There is a command: "/enviroquake  start"
and you can stop it.

**Comment by jasonsaffle13** [comment]
with /enviroquakestop i guess?

**Comment by GenDeathrow** [comment]
yes

**Comment by jasonsaffle13** [comment]
will copy world folder first then cause one will report if it crashes

**Comment by GenDeathrow** [comment]
start an earthquake in an ocean.. See if that causes a crash

**Comment by jasonsaffle13** [comment]
upgraded to 104 but server will not start i get this:
http://paste.ubuntu.com/10333713/

**Comment by GenDeathrow** [comment]
Yes server is a issue on 104. I was going to try to get a hot fix tonight.

**Comment by GenDeathrow** [comment]
105 should fix server crash

**Comment by jasonsaffle13** [comment]
http://paste.ubuntu.com/10362071/

**Comment by Funwayguy** [comment]
I think I know what that might. I'll have to take a look at it later to be sure though

**Comment by itbones** [comment]
@GenDeathrow Had this crash running version 105. (Crashlog here)[http://pastebin.com/ZqHaLej3]

**Comment by Funwayguy** [comment]
Should be fixed now

**Comment by ignatio** [comment]
Not resolved: http://pastebin.com/01fCDud2 still crashing nosuchfeild errors for clientQuake in 106

**Comment by sabi666** [comment]
same issue with 106 and cant go back to older version cause of " UNAUTHORIZED USE OF MOD ENVIROMINE" error

**Comment by Funwayguy** [comment]
-_- I'm working on it

**Comment by Funwayguy** [comment]
Made a stupid error in the last patch so I fixed that up and I set off a couple of earthquakes server side just to be sure it is indeed fixed now... I need a new test world now.

**Comment by jasonsaffle13** [comment]
If I set off an earthquake it would NOT crash but if one happens on it's own THEN I crash.

**Comment by Funwayguy** [comment]
I've pushed out the fixed build.

**Comment by DKPooter** [comment]
appreciate the work. Thanks!

**Comment by jasonsaffle13** [comment]
works for me as well now!! Except the quake has been running non stop for over an hour!!

**Comment by Funwayguy** [comment]
You'll probably have to increase the speed in the settings. Sometimes it does tend to take a long time to cut through the world.
